# Generated by Django 3.2.19 on 2023-06-23 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
                ('program_type', models.CharField(choices=[('Specialist', 'SPE'), ('Major', 'MAJ'), ('Minor', 'MIN')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('requirement', models.TextField(max_length=2500)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
            ],
        ),
    ]
