# Generated by Django 4.2.2 on 2023-06-17 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
                ('program_type', models.CharField(choices=[('SPE', 'Specialist'), ('MAJ', 'Major'), ('MIN', 'Minor')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='requirement',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('requirement', models.TextField(max_length=2500)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
            ],
        ),
    ]
