# Generated by Django 4.2.2 on 2023-07-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_exclusions_algo_course_pre_req_algo'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='program_name',
            new_name='program_title',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_id',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_type',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='program',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='requirement',
        ),
        migrations.AddField(
            model_name='program',
            name='program_code',
            field=models.CharField(default='00000', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='program',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='programs.requirement'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='count',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='requirement',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='requirement_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='requirement',
            name='requirement_type',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
