# Generated by Django 4.2.2 on 2023-06-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='program_id',
            new_name='program',
        ),
    ]
