# Generated by Django 4.2.2 on 2023-06-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_rename_program_id_requirement_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('Specialist', 'SPE'), ('Major', 'MAJ'), ('Minor', 'MIN')], max_length=100),
        ),
    ]
