# Generated by Django 4.2.2 on 2023-07-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_rename_program_name_program_program_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='categories',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
