# Generated by Django 4.2.2 on 2023-06-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinereviews',
            old_name='course',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='userreviews',
            old_name='course',
            new_name='course_code',
        ),
        migrations.AlterField(
            model_name='onlinereviews',
            name='senitment_analysis_value',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
