# Generated by Django 4.2.2 on 2023-06-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinereview',
            old_name='senitment_analysis_value',
            new_name='sentiment_analysis_value',
        ),
    ]
