# Generated by Django 4.2.2 on 2023-07-08 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_senitment_analysis_value_onlinereview_sentiment_analysis_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='Professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.professor'),
        ),
    ]
