# Generated by Django 4.2.2 on 2023-06-19 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_course_onlinereviews_course_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinereviews',
            old_name='course_code',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='userreviews',
            old_name='course_code',
            new_name='course',
        ),
    ]
