# Generated by Django 4.2.2 on 2023-06-19 22:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_distrubution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_rename_course_code_onlinereviews_course_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OnlineReviews',
            new_name='OnlineReview',
        ),
        migrations.RenameModel(
            old_name='UserReviews',
            new_name='UserReview',
        ),
    ]
