# Generated by Django 4.2.2 on 2023-07-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_avg_rating'),
        ('reviews', '0004_alter_userreview_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='previous_courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
