# Generated by Django 4.2.2 on 2023-07-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_professor_previous_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='userName',
            new_name='username',
        ),
    ]
