# Generated by Django 3.2.19 on 2023-06-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('credit', models.DecimalField(decimal_places=1, max_digits=3)),
                ('recommended_prep', models.TextField(default='')),
                ('distrubution', models.CharField(choices=[('Science', 'SCI'), ('Humanities', 'HUM'), ('Social Science', 'SSC'), ('None', 'N/A')], max_length=14)),
                ('pre_req', models.TextField(default='')),
                ('exclusions', models.TextField(default='')),
                ('description', models.TextField()),
            ],
        ),
    ]
