# Generated by Django 4.2.2 on 2023-06-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exclusions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.JSONField(default=list),
        ),
    ]
