# Generated by Django 4.2.2 on 2023-06-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='programArea',
            field=models.CharField(default='', max_length=200),
        ),
    ]
