# Generated by Django 4.2.2 on 2023-06-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_exclusions_alter_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='recommended_prep',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='distrubution',
            field=models.CharField(choices=[('SCI', 'Science'), ('HUM', 'Humanities'), ('SSC', 'Social Science'), ('N/A', 'None')], max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='exclusions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(default=''),
        ),
    ]
