# Generated by Django 4.2.2 on 2023-06-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_recommended_prep_alter_course_distrubution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='credits',
            new_name='credit',
        ),
    ]
