# Generated by Django 4.2.2 on 2023-07-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_programarea_course_program_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='course',
            name='num_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
