# Generated by Django 4.2.2 on 2023-07-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_avg_rating_course_num_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='distrubution',
            new_name='distribution',
        ),
    ]
