# Generated by Django 4.2.2 on 2023-07-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
