# Generated by Django 4.2.2 on 2023-07-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exclusions_algo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='pre_req_algo',
            field=models.TextField(default=''),
        ),
    ]
