# Generated by Django 4.2.2 on 2023-07-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_is_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=3),
        ),
    ]
